;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ignore
	indent-for-tab-command
	multiple-cursors-mode
	))

(setq mc/cmds-to-run-once
      '(
	asm-comment
	ignore
	))
